export const publicAssetPreloadPaths = {
  image: [
    '/share-cover.png',
    '/optimized/flower-left.webp',
    '/optimized/flower-right.webp',
    '/optimized/petal-1.webp',
    '/optimized/petal-2.webp',
    '/optimized/petal-3.webp',
    '/optimized/couple-photo-4601.webp',
    '/optimized/gallery/IMGL4513.webp',
    '/optimized/gallery/IMGL4519.webp',
    '/optimized/gallery/IMGL4578.webp',
    '/optimized/gallery/IMGL4623.webp',
    '/optimized/gallery/IMGL4651.webp',
    '/optimized/gallery/IMGL4677-closing.webp',
    '/optimized/gallery/IMGL4748.webp',
    '/optimized/gallery/IMGL4914.webp',
    '/optimized/gallery/IMGL4938.webp',
    '/optimized/gallery/IMGL4949.webp',
    '/optimized/gallery/IMGL4980.webp',
    '/optimized/gallery/IMGL4985.webp',
    '/optimized/gallery/IMGL4991.webp',
    '/optimized/gallery/IMGL5055.webp',
    '/optimized/gallery/proposal-3.webp',
    '/optimized/gallery/proposal.webp',
    '/optimized/gallery/proposal-ring.webp',
    '/optimized/cinematic/IMGL4964.webp',
    '/optimized/cinematic/IMGL5105.webp',
    '/optimized/cinematic/IMGL5133.webp',
    '/optimized/contact/bride-cutout.webp',
    '/optimized/contact/groom-cutout.webp',
  ],
  audio: ['/wedding-music.mp3'],
};

export const publicAssetPreloads = [
  ...publicAssetPreloadPaths.image.map((path) => ({ as: 'image', path })),
  ...publicAssetPreloadPaths.audio.map((path) => ({ as: 'audio', path })),
];
